[package]
name = "uiviewer"
version = "0.1.0"
edition = "2021"
rust-version = "1.92"

[dependencies]
eframe = "0.35"
egui = "0.35"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
roxmltree = "0.19"
rfd = "0.14"
serde_json = { version = "1.0.150", default-features = false, features = ["std"] }
base64 = "0.22"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
